[pytest]

markers =
    smoke: Critical functionality tests
    sanity: Basic validation tests
    regression: Full regression tests

addopts = -q --disable-warnings

filterwarnings =
    ignore:usefixtures\(\) in .* has no effect:pytest.PytestWarning
    ignore::DeprecationWarning
